export enum ClientEvent {
  JOIN = 'JOIN',
  HOVER = 'HOVER',
  MAKE_MOVE = 'MAKE_MOVE',
  START_MATCH = 'START_MATCH',
  DISCONNECT_FROM_MATCH = 'DISCONNECT_FROM_MATCH',
  UPDATE_GAME_SETTINGS = 'UPDATE_GAME_SETTINGS',
  KICK_PARTICIPANT = 'KICK_PARTICIPANT',
}
