export enum ServerEvent {
  JOINED = "JOINED",
  MADE_MOVE = "MADE_MOVE",
  TURN_TIMER_RAN_OUT = "TURN_TIMER_RAN_OUT",
  HOVERED = "HOVERED",
  STARTED_MATCH = "STARTED_MATCH",
  PLAYER_CONNECTED_TO_MATCH = "PLAYER_CONNECTED_TO_MATCH",
  PLAYER_DISCONNECTED_FROM_MATCH = "PLAYER_DISCONNECTED_FROM_MATCH",
  UPDATED_GAME_SETTINGS = "UPDATED_GAME_SETTINGS",
  KICKED_PARTICIPANT = "KICKED_PARTICIPANT",
  ERROR = "ERROR",
}
